### ISSUE TITLE
Асинхронный сетстейт

### ISSUE THREAD

**Issue by artrnh** [JohnDeeBeeCooper/pizza#1]
Короче сетстейт может быть асинхронным, поэтому старайся не использовать в нём this.state, если нужно использовать предыдущий стейт, то передавай в сетСтейт коллбек, ему первым аргументом и придет prevState.

https://github.com/JohnDeeBeeCooper/pizza/blob/8ff41b19967b327ca048b38c392536af36f1fc1f/src/components/App.jsx#L15

**Comment by JohnDeeBeeCooper** [comment]
пошел нахуй
